config/routes.rb
AjicomHtml::Application.routes.draw do
    
  resources :mtopicuses

  resources :mcompanytypes

  resources :mnotices

  resources :tcheckbytopics

  resources :global_searches do
    collection do
      get 'search'
      post 'search'
    end
  end

  resources :tstaffbycomps

  resources :mcategories

  get "welcome/index"

  resources :roles

  root :to => "welcome#index"
  
  devise_for :user
  
  devise_for :users, :only => [:session] do
    get '/sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get '/sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
    get '/forgot_password', :to => 'devise/passwords#new', :as => :new_password_session
  end
  
  resources :users do
    get :new
    post :create
    post :destroy
  end
  
  resources :vdivbycomps

  resources :tworkbycomps

  resources :tuserbycomps

  resources :tfilebytopics do
    collection do
      get  'upload'
      post 'upload'
    end
  end

  resources :texpertbycomps

  resources :tcategorybytopics

  resources :mworkgroups

  resources :mworkareasubs

  resources :mworkareas

  resources :musers do
    collection do
      get 'search'
      get 'ajicom_new'
      post 'search'
    end
  end

  resources :mgenerals

  resources :mexpertises

  resources :mcompusers

  resources :mcompanies do
    member do
      get 'order_by_company_name'
      
    end

    collection do
      get 'order_by_company_name'
      get 'search'
      get 'add_ajicom_user'
      get 'add_staff'
      get 'get_address_data'
      get 'popup'
      post 'popup'
      post 'search'
    end
  end
  
  resources :contents
  
  match '/ttopics/client_select'
  match '/ttopics/cmbbrand'
  match '/ttopics/cmbclient_id'
  match '/ttopics/cmbmcompany_id'
  match '/ttopics/cmbmprinting_company'
  resources :ttopics do
    collection do
      get 'history'
      get 'whatsnew'
      get 'search'
      get 'client_select'
      post 'search'
    end
  end

  resources :mbrands do
    collection do
      get 'popup'
      post 'popup'
    end
  end
  

end

app/models/content.rb
class Content < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @contents }
    end
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
    @content = Content.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @content }
    end
  end

  # GET /contents/new
  # GET /contents/new.json
  def new
    @content = Content.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @content }
    end
  end

  # GET /contents/1/edit
  def edit
    @content = Content.find(params[:id])
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(params[:content])

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, :notice => 'Content was successfully created.' }
        format.json { render :json => @content, :status => :created, :location => @content }
      else
        format.html { render :action => "new" }
        format.json { render :json => @content.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /contents/1
  # PUT /contents/1.json
  def update
    @content = Content.find(params[:id])

    respond_to do |format|
      if @content.update_attributes(params[:content])
        format.html { redirect_to @content, :notice => 'Content was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @content.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content = Content.find(params[:id])
    @content.destroy

    respond_to do |format|
      format.html { redirect_to contents_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.erb
<%= form_for(@content) do |f| %>
  <% if @content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% @content.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Editing content</h1>

<%= render 'form' %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/index.html.erb
<h1>Listing contents</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contents.each do |content| %>
  <tr>
    <td><%= link_to 'Show', content %></td>
    <td><%= link_to 'Edit', edit_content_path(content) %></td>
    <td><%= link_to 'Destroy', content, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Content', new_content_path %>

app/views/contents/new.html.erb
<h1>New content</h1>

<%= render 'form' %>

<%= link_to 'Back', contents_path %>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_content_path(@content) %> |
<%= link_to 'Back', contents_path %>