config/routes.rb
AjicomHtml::Application.routes.draw do
    
  resources :mtopicuses

  resources :mcompanytypes

  resources :mnotices

  resources :tcheckbytopics

  resources :global_searches do
    collection do
      get 'search'
      post 'search'
    end
  end

  resources :tstaffbycomps

  resources :mcategories

  get "welcome/index"

  resources :roles

  root :to => "welcome#index"
  
  devise_for :user
  
  devise_for :users, :only => [:session] do
    get '/sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get '/sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
    get '/forgot_password', :to => 'devise/passwords#new', :as => :new_password_session
  end
  
  resources :users do
    get :new
    post :create
    post :destroy
  end
  
  resources :vdivbycomps

  resources :tworkbycomps

  resources :tuserbycomps

  resources :tfilebytopics do
    collection do
      get  'upload'
      post 'upload'
    end
  end

  resources :texpertbycomps

  resources :tcategorybytopics

  resources :mworkgroups

  resources :mworkareasubs

  resources :mworkareas

  resources :musers do
    collection do
      get 'search'
      get 'ajicom_new'
      post 'search'
    end
  end

  resources :mgenerals

  resources :mexpertises

  resources :mcompusers

  resources :mcompanies do
    member do
      get 'order_by_company_name'
      
    end

    collection do
      get 'order_by_company_name'
      get 'search'
      get 'add_ajicom_user'
      get 'add_staff'
      get 'get_address_data'
      get 'popup'
      post 'popup'
      post 'search'
    end
  end
  
  resources :contents
  
  match '/ttopics/client_select'
  match '/ttopics/cmbbrand'
  match '/ttopics/cmbclient_id'
  match '/ttopics/cmbmcompany_id'
  match '/ttopics/cmbmprinting_company'
  resources :ttopics do
    collection do
      get 'history'
      get 'whatsnew'
      get 'search'
      get 'client_select'
      post 'search'
    end
  end

  resources :mbrands do
    collection do
      get 'popup'
      post 'popup'
    end
  end
  

end

app/models/mcategory.rb
class Mcategory < ActiveRecord::Base
  attr_accessible :another_name, :created_by, :name, :updated_by
  
  has_many:tcategorybytopics
end

app/controllers/mcategories_controller.rb
class McategoriesController < ApplicationController
  # GET /mcategories
  # GET /mcategories.json
  def index
    @mcategories = Mcategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @mcategories }
    end
  end

  # GET /mcategories/1
  # GET /mcategories/1.json
  def show
    @mcategory = Mcategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @mcategory }
    end
  end

  # GET /mcategories/new
  # GET /mcategories/new.json
  def new
    @mcategory = Mcategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @mcategory }
    end
  end

  # GET /mcategories/1/edit
  def edit
    @mcategory = Mcategory.find(params[:id])
  end

  # POST /mcategories
  # POST /mcategories.json
  def create
    @mcategory = Mcategory.new(params[:mcategory])

    respond_to do |format|
      if @mcategory.save
        format.html { redirect_to @mcategory, :notice => 'Mcategory was successfully created.' }
        format.json { render :json => @mcategory, :status => :created, :location => @mcategory }
      else
        format.html { render :action => "new" }
        format.json { render :json => @mcategory.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /mcategories/1
  # PUT /mcategories/1.json
  def update
    @mcategory = Mcategory.find(params[:id])

    respond_to do |format|
      if @mcategory.update_attributes(params[:mcategory])
        format.html { redirect_to @mcategory, :notice => 'Mcategory was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @mcategory.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /mcategories/1
  # DELETE /mcategories/1.json
  def destroy
    @mcategory = Mcategory.find(params[:id])
    @mcategory.destroy

    respond_to do |format|
      format.html { redirect_to mcategories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/mcategories_helper.rb
module McategoriesHelper
end

app/views/mcategories/_form.html.erb
<%= simple_form_for(@mcategory) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :another_name %>
    <%= f.input :created_by %>
    <%= f.input :updated_by %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/mcategories/edit.html.erb
<h1>Editing mcategory</h1>

<%= render 'form' %>

<%= link_to 'Show', @mcategory %> |
<%= link_to 'Back', mcategories_path %>

app/views/mcategories/index.html.erb
<h1>Listing mcategories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Another name</th>
    <th>Created by</th>
    <th>Updated by</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mcategories.each do |mcategory| %>
  <tr>
    <td><%= mcategory.name %></td>
    <td><%= mcategory.another_name %></td>
    <td><%= mcategory.created_by %></td>
    <td><%= mcategory.updated_by %></td>
    <td><%= link_to 'Show', mcategory %></td>
    <td><%= link_to 'Edit', edit_mcategory_path(mcategory) %></td>
    <td><%= link_to 'Destroy', mcategory, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mcategory', new_mcategory_path %>

app/views/mcategories/new.html.erb
<h1>New mcategory</h1>

<%= render 'form' %>

<%= link_to 'Back', mcategories_path %>

app/views/mcategories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @mcategory.name %>
</p>

<p>
  <b>Another name:</b>
  <%= @mcategory.another_name %>
</p>

<p>
  <b>Created by:</b>
  <%= @mcategory.created_by %>
</p>

<p>
  <b>Updated by:</b>
  <%= @mcategory.updated_by %>
</p>


<%= link_to 'Edit', edit_mcategory_path(@mcategory) %> |
<%= link_to 'Back', mcategories_path %>