config/routes.rb
AjicomHtml::Application.routes.draw do
    
  resources :mtopicuses

  resources :mcompanytypes

  resources :mnotices

  resources :tcheckbytopics

  resources :global_searches do
    collection do
      get 'search'
      post 'search'
    end
  end

  resources :tstaffbycomps

  resources :mcategories

  get "welcome/index"

  resources :roles

  root :to => "welcome#index"
  
  devise_for :user
  
  devise_for :users, :only => [:session] do
    get '/sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get '/sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
    get '/forgot_password', :to => 'devise/passwords#new', :as => :new_password_session
  end
  
  resources :users do
    get :new
    post :create
    post :destroy
  end
  
  resources :vdivbycomps

  resources :tworkbycomps

  resources :tuserbycomps

  resources :tfilebytopics do
    collection do
      get  'upload'
      post 'upload'
    end
  end

  resources :texpertbycomps

  resources :tcategorybytopics

  resources :mworkgroups

  resources :mworkareasubs

  resources :mworkareas

  resources :musers do
    collection do
      get 'search'
      get 'ajicom_new'
      post 'search'
    end
  end

  resources :mgenerals

  resources :mexpertises

  resources :mcompusers

  resources :mcompanies do
    member do
      get 'order_by_company_name'
      
    end

    collection do
      get 'order_by_company_name'
      get 'search'
      get 'add_ajicom_user'
      get 'add_staff'
      get 'get_address_data'
      get 'popup'
      post 'popup'
      post 'search'
    end
  end
  
  resources :contents
  
  match '/ttopics/client_select'
  match '/ttopics/cmbbrand'
  match '/ttopics/cmbclient_id'
  match '/ttopics/cmbmcompany_id'
  match '/ttopics/cmbmprinting_company'
  resources :ttopics do
    collection do
      get 'history'
      get 'whatsnew'
      get 'search'
      get 'client_select'
      post 'search'
    end
  end

  resources :mbrands do
    collection do
      get 'popup'
      post 'popup'
    end
  end
  

end

app/models/mcompuser.rb
class Mcompuser < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/mcompusers_controller.rb
class McompusersController < ApplicationController
  # GET /mcompusers
  # GET /mcompusers.json
  def index
    @mcompusers = Mcompuser.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @mcompusers }
    end
  end

  # GET /mcompusers/1
  # GET /mcompusers/1.json
  def show
    @mcompuser = Mcompuser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @mcompuser }
    end
  end

  # GET /mcompusers/new
  # GET /mcompusers/new.json
  def new
    @mcompuser = Mcompuser.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @mcompuser }
    end
  end

  # GET /mcompusers/1/edit
  def edit
    @mcompuser = Mcompuser.find(params[:id])
  end

  # POST /mcompusers
  # POST /mcompusers.json
  def create
    @mcompuser = Mcompuser.new(params[:mcompuser])

    respond_to do |format|
      if @mcompuser.save
        format.html { redirect_to @mcompuser, :notice => 'Mcompuser was successfully created.' }
        format.json { render :json => @mcompuser, :status => :created, :location => @mcompuser }
      else
        format.html { render :action => "new" }
        format.json { render :json => @mcompuser.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /mcompusers/1
  # PUT /mcompusers/1.json
  def update
    @mcompuser = Mcompuser.find(params[:id])

    respond_to do |format|
      if @mcompuser.update_attributes(params[:mcompuser])
        format.html { redirect_to @mcompuser, :notice => 'Mcompuser was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @mcompuser.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /mcompusers/1
  # DELETE /mcompusers/1.json
  def destroy
    @mcompuser = Mcompuser.find(params[:id])
    @mcompuser.destroy

    respond_to do |format|
      format.html { redirect_to mcompusers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/mcompusers_helper.rb
module McompusersHelper
end

app/views/mcompusers/_form.html.erb
<%= form_for(@mcompuser) do |f| %>
  <% if @mcompuser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mcompuser.errors.count, "error") %> prohibited this mcompuser from being saved:</h2>

      <ul>
      <% @mcompuser.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mcompusers/edit.html.erb
<h1>Editing mcompuser</h1>

<%= render 'form' %>

<%= link_to 'Show', @mcompuser %> |
<%= link_to 'Back', mcompusers_path %>

app/views/mcompusers/index.html.erb
<h1>Listing mcompusers</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mcompusers.each do |mcompuser| %>
  <tr>
    <td><%= link_to 'Show', mcompuser %></td>
    <td><%= link_to 'Edit', edit_mcompuser_path(mcompuser) %></td>
    <td><%= link_to 'Destroy', mcompuser, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mcompuser', new_mcompuser_path %>

app/views/mcompusers/new.html.erb
<h1>New mcompuser</h1>

<%= render 'form' %>

<%= link_to 'Back', mcompusers_path %>

app/views/mcompusers/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_mcompuser_path(@mcompuser) %> |
<%= link_to 'Back', mcompusers_path %>