config/routes.rb
AjicomHtml::Application.routes.draw do
    
  resources :mtopicuses

  resources :mcompanytypes

  resources :mnotices

  resources :tcheckbytopics

  resources :global_searches do
    collection do
      get 'search'
      post 'search'
    end
  end

  resources :tstaffbycomps

  resources :mcategories

  get "welcome/index"

  resources :roles

  root :to => "welcome#index"
  
  devise_for :user
  
  devise_for :users, :only => [:session] do
    get '/sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get '/sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
    get '/forgot_password', :to => 'devise/passwords#new', :as => :new_password_session
  end
  
  resources :users do
    get :new
    post :create
    post :destroy
  end
  
  resources :vdivbycomps

  resources :tworkbycomps

  resources :tuserbycomps

  resources :tfilebytopics do
    collection do
      get  'upload'
      post 'upload'
    end
  end

  resources :texpertbycomps

  resources :tcategorybytopics

  resources :mworkgroups

  resources :mworkareasubs

  resources :mworkareas

  resources :musers do
    collection do
      get 'search'
      get 'ajicom_new'
      post 'search'
    end
  end

  resources :mgenerals

  resources :mexpertises

  resources :mcompusers

  resources :mcompanies do
    member do
      get 'order_by_company_name'
      
    end

    collection do
      get 'order_by_company_name'
      get 'search'
      get 'add_ajicom_user'
      get 'add_staff'
      get 'get_address_data'
      get 'popup'
      post 'popup'
      post 'search'
    end
  end
  
  resources :contents
  
  match '/ttopics/client_select'
  match '/ttopics/cmbbrand'
  match '/ttopics/cmbclient_id'
  match '/ttopics/cmbmcompany_id'
  match '/ttopics/cmbmprinting_company'
  resources :ttopics do
    collection do
      get 'history'
      get 'whatsnew'
      get 'search'
      get 'client_select'
      post 'search'
    end
  end

  resources :mbrands do
    collection do
      get 'popup'
      post 'popup'
    end
  end
  

end

app/models/vdivbycomp.rb
class Vdivbycomp < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/vdivbycomps_controller.rb
class VdivbycompsController < ApplicationController
  # GET /vdivbycomps
  # GET /vdivbycomps.json
  def index
    @vdivbycomps = Vdivbycomp.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @vdivbycomps }
    end
  end

  # GET /vdivbycomps/1
  # GET /vdivbycomps/1.json
  def show
    @vdivbycomp = Vdivbycomp.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @vdivbycomp }
    end
  end

  # GET /vdivbycomps/new
  # GET /vdivbycomps/new.json
  def new
    @vdivbycomp = Vdivbycomp.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @vdivbycomp }
    end
  end

  # GET /vdivbycomps/1/edit
  def edit
    @vdivbycomp = Vdivbycomp.find(params[:id])
  end

  # POST /vdivbycomps
  # POST /vdivbycomps.json
  def create
    @vdivbycomp = Vdivbycomp.new(params[:vdivbycomp])

    respond_to do |format|
      if @vdivbycomp.save
        format.html { redirect_to @vdivbycomp, :notice => 'Vdivbycomp was successfully created.' }
        format.json { render :json => @vdivbycomp, :status => :created, :location => @vdivbycomp }
      else
        format.html { render :action => "new" }
        format.json { render :json => @vdivbycomp.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /vdivbycomps/1
  # PUT /vdivbycomps/1.json
  def update
    @vdivbycomp = Vdivbycomp.find(params[:id])

    respond_to do |format|
      if @vdivbycomp.update_attributes(params[:vdivbycomp])
        format.html { redirect_to @vdivbycomp, :notice => 'Vdivbycomp was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @vdivbycomp.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /vdivbycomps/1
  # DELETE /vdivbycomps/1.json
  def destroy
    @vdivbycomp = Vdivbycomp.find(params[:id])
    @vdivbycomp.destroy

    respond_to do |format|
      format.html { redirect_to vdivbycomps_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/vdivbycomps_helper.rb
module VdivbycompsHelper
end

app/views/vdivbycomps/_form.html.erb
<%= form_for(@vdivbycomp) do |f| %>
  <% if @vdivbycomp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vdivbycomp.errors.count, "error") %> prohibited this vdivbycomp from being saved:</h2>

      <ul>
      <% @vdivbycomp.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vdivbycomps/edit.html.erb
<h1>Editing vdivbycomp</h1>

<%= render 'form' %>

<%= link_to 'Show', @vdivbycomp %> |
<%= link_to 'Back', vdivbycomps_path %>

app/views/vdivbycomps/index.html.erb
<h1>Listing vdivbycomps</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @vdivbycomps.each do |vdivbycomp| %>
  <tr>
    <td><%= link_to 'Show', vdivbycomp %></td>
    <td><%= link_to 'Edit', edit_vdivbycomp_path(vdivbycomp) %></td>
    <td><%= link_to 'Destroy', vdivbycomp, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vdivbycomp', new_vdivbycomp_path %>

app/views/vdivbycomps/new.html.erb
<h1>New vdivbycomp</h1>

<%= render 'form' %>

<%= link_to 'Back', vdivbycomps_path %>

app/views/vdivbycomps/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_vdivbycomp_path(@vdivbycomp) %> |
<%= link_to 'Back', vdivbycomps_path %>